#!/usr/bin/env python3
"""Convert project PNG art to LVGL 9 little-endian ARGB8888 resources.

Only resizes and packs pixels; no semantic image editing or background removal.
Requires Pillow. Run from any directory. Original PNGs are never modified.
"""
import hashlib
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets/portraits'
OUT = ROOT / 'app/hello_app/ui/ebadge_portraits.c'
SIZE = 372


def main():
    chunks = ['/* Generated by tools/generate_portraits.py; do not hand-edit. */',
              '#include "ebadge_portraits.h"', '']
    records = []
    for index, name in enumerate(('taitai-v1', 'nuannuan-v1', 'yueyue-v1')):
        source = ASSETS / (name + '.png')
        with Image.open(source) as original:
            if original.width != original.height:
                raise ValueError('Expected square source: ' + name)
            rgba = original.convert('RGBA')
            if rgba.getchannel('A').getextrema()[0] != 0:
                raise ValueError('Source lacks the requested transparency: ' + name)
            original_size = list(original.size)
            rgba = rgba.resize((SIZE, SIZE), Image.Resampling.LANCZOS)
            pixels = rgba.tobytes('raw', 'BGRA')
        chunks.append('static const LV_ATTRIBUTE_MEM_ALIGN uint8_t pixels_%d[] = {' % index)
        for offset in range(0, len(pixels), 24):
            chunks.append('  ' + ','.join('0x%02x' % b for b in pixels[offset:offset + 24]) + ',')
        chunks.append('};\n')
        records.append({'id': index, 'file': 'assets/portraits/' + source.name,
                        'source_size': original_size,
                        'source_sha256': hashlib.sha256(source.read_bytes()).hexdigest(),
                        'packed_size': [SIZE, SIZE], 'packed_bytes': len(pixels),
                        'format': 'LV_COLOR_FORMAT_ARGB8888 / little-endian BGRA',
                        'origin': 'AI-generated original project artwork'})
    chunks.append('const lv_image_dsc_t ebadge_portraits[3] = {')
    for index in range(3):
        chunks.append('  {.header = {.magic = LV_IMAGE_HEADER_MAGIC, '
                      '.cf = LV_COLOR_FORMAT_ARGB8888, .flags = 0, '
                      '.w = %d, .h = %d, .stride = %d}, '
                      '.data_size = sizeof(pixels_%d), .data = pixels_%d},' %
                      (SIZE, SIZE, SIZE * 4, index, index))
    chunks.append('};\n')
    OUT.write_text('\n'.join(chunks))
    (ASSETS / 'manifest.json').write_text(json.dumps(records, indent=2) + '\n')
    print(json.dumps({'portraits': len(records), 'packed_total_bytes':
                      sum(r['packed_bytes'] for r in records), 'output': str(OUT)}))


if __name__ == '__main__':
    main()
