#!/usr/bin/env python3
"""Pack local THA3 RGBA frames for LVGL; no model inference or upload."""
import hashlib
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'design/taitai-motion-tha3/frames'
OUTPUT = ROOT / 'app/hello_app/ui/ebadge_motion.c'
NAMES = ('neutral', 'blink035', 'blink070', 'blink100', 'right004',
         'right008', 'right012', 'left004', 'left008', 'left012')


def main():
    records = []
    with OUTPUT.open('w') as output:
        output.write('/* Generated by tools/pack_taitai_motion.py.\n'
                     ' * THA3 by pkhungurn; models CC-BY-4.0, code MIT.\n'
                     ' * Derived from original project artwork; posed and cropped.\n'
                     ' */\n#include "ebadge_motion.h"\n')
        for index, name in enumerate(NAMES):
            path = SOURCE / (name + '.png')
            with Image.open(path) as image:
                if image.size != (512, 512):
                    raise ValueError('Expected THA3 512x512 frame: ' + name)
                pixels = image.convert('RGBA').crop((112, 0, 400, 288)).tobytes('raw', 'BGRA')
            output.write('static const LV_ATTRIBUTE_MEM_ALIGN uint8_t motion_%d[] = {\n' % index)
            for start in range(0, len(pixels), 24):
                output.write('  ' + ','.join('0x%02x' % b for b in pixels[start:start+24]) + ',\n')
            output.write('};\n')
            records.append({'index': index, 'name': name, 'bytes': len(pixels),
                            'source_sha256': hashlib.sha256(path.read_bytes()).hexdigest()})
        output.write('const lv_image_dsc_t ebadge_motion_frames[EBADGE_MOTION_FRAME_COUNT] = {\n')
        for index in range(len(NAMES)):
            output.write('  {.header = {.magic = LV_IMAGE_HEADER_MAGIC, '
                         '.cf = LV_COLOR_FORMAT_ARGB8888, .flags = 0, '
                         '.w = 288, .h = 288, .stride = 1152}, '
                         '.data_size = sizeof(motion_%d), .data = motion_%d},\n' % (index, index))
        output.write('};\n')
    manifest = {'engine': 'THA3 separable_float', 'model_author': 'pkhungurn',
                'model_license': 'CC-BY-4.0',
                'upstream': 'https://github.com/pkhungurn/talking-head-anime-3-demo',
                'crop': [112, 0, 400, 288], 'format': 'ARGB8888 little-endian BGRA',
                'frames': records, 'total_bytes': sum(r['bytes'] for r in records)}
    (ROOT / 'design/taitai-motion-tha3/firmware-assets.json').write_text(json.dumps(manifest, indent=2)+'\n')
    print(json.dumps({'frames': len(records), 'bytes': manifest['total_bytes'], 'output': str(OUTPUT)}))


if __name__ == '__main__':
    main()
